dependencies:
  - ffmpeg
  - pip

  - pip:
    - -e .
    - click
    - coverage
    - python-dotenv
    - pydub
    - openai
    - markdown-it-py
    - mdit_plain
    - json_repair
    - names_generator
  
# EOF
