dependencies:
  - ffmpeg
  - pip

  - pip:
    ## development environment external requirements,
    ## those dependencies are considered for rinning development environment
    - click  # to simplify working with argument parsin in scripts
    - build  # to allow build WHL pachages
    - ipykernel # to make conda env appear as kernel
    - nbdime # to allow GIT to work with jupyter notebooks, integrate with git using `nbdime config-git --enable --global`
    - pytest # for running python test
    - pytest-cov # for running python test coverage report
    - toml   # for working with .toml files
  
    # local package
    - -e .

# EOF
