FILE_AUDIO_STATS_CSV = '../../data/processed/henryk_audio_stats.csv'
FILE_TRANSCRIPTION_CSV = '../../data/processed/henryk_audio_transcription.csv'
DIR_WIADOMOSCI_DO_HENRYCZKA = '/mnt/onedrive/My Private/My documents/Other/Henryk/Alienacja rodzicielska materiały/Wiadomości do Henryczka'
DIR_WHCLI = '../../whcli'
DIR_TRANSCRIPTIONS = '../../data/processed/transcriptions'